global using Basket.API.Models;
global using Ecart.Core.CQRS;
global using Carter;
global using MediatR;
global using Mapster;
global using FluentValidation;
global using Ecart.Core.Behaviors;
global using Ecart.Core.Exceptions;
global using Basket.API.Dtos;
